In [25]:
import numpy as np

In [26]:
def solve(a,b,c):
    arr1 = np.full((a,b),c)
    return arr1
solve(3,3,5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [27]:
def sum_arr(*arr):
    ls = [*arr]
    arr2 = [0]
    for arr in ls:
        arr2 = arr2+arr
    return arr2

x = np.array([[1,5],[1,6]])
y = np.array([[5,9],[6,7]])
z = np.array([[6,10],[8,9]])
a = np.array([[5,10],[6,9]])

sum_arr(x,y,z,a)

array([[17, 34],
       [21, 31]])

In [28]:
def slic(arr,n,m):
    slic1 = arr[:n,:m]
    return slic1
x = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
slic(x,2,2)

array([[1, 2],
       [4, 5]])

In [29]:
def slic(arr,n,m):
    slic1 = arr[n:,m:]
    return slic1
x = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
slic(x,1,1)

array([[5, 6],
       [8, 9]])

In [30]:
def stat(a):
    std_dev = np.std(a)
    mean = np.mean(a)
    dic = {"mean":mean,"std_dev":std_dev}
    return dic
x = [1,1,1]
stat(x)

{'mean': 1.0, 'std_dev': 0.0}