In [1]:
import numpy as np

In [7]:
arr = np.arange(2,11)
arr.resize(3,3)
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [30]:
narr = np.random.randint(2,10, size=(3,3))
narr

array([[9, 9, 9],
       [6, 4, 5],
       [4, 3, 9]])

In [11]:
arr1 = np.array([1,2,3,4])
arr1.astype(float)

array([1., 2., 3., 4.])

In [14]:
arr2 = np.array([10,20,30])
np.append(arr2, [40,50,60,70,80,90])

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [25]:
narr1 = np.array([1,2,3,4])
narr2 = np.array([5,6,7,8])
sumArray = []
for i in range(0, narr1.shape[0]):
    sumArray.append(narr1[i]+narr2[i])
np.array(sumArray)


array([ 6,  8, 10, 12])

In [28]:
arr3 = np.random.randint(10,90, size=(3,3))
arr3

array([[32, 56, 85],
       [17, 79, 46],
       [40, 85, 23]])

In [33]:
arr3[0:1]

array([[32, 56, 85]])

In [38]:
arr3[2:,2:]

array([[23]])